<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<script lang="ts" module>
  // Single source of truth for icons. Every icon in the app comes from here, so
  // the icon set can be swapped or upgraded in ONE place. Add new icons to this
  // registry as needed — nothing else imports `@lucide/svelte` directly.
  import {
    Feather,
    Home,
    LogIn,
    LogOut,
    PenLine,
    User as UserIcon,
    UserPlus,
    UserMinus,
    LoaderCircle,
    Search,
    Settings,
    MoreHorizontal,
    BookOpen,
    Sparkles,
    Globe,
    Clock,
    Users,
    Bold,
    Italic,
    Strikethrough,
    Code,
    Code2,
    Link as LinkIcon,
    Minus,
    Heading,
    Heading1,
    Heading2,
    Heading3,
    Heading4,
    Heading5,
    Heading6,
    Pilcrow,
    ListOrdered,
    List,
    Quote,
    ChevronDown,
    Sun,
    Moon,
    Monitor,
    Camera,
    Pencil,
    X,
    Heart,
    MessageCircle,
    Reply,
    Trash2,
    Share,
    Check,
    Image as ImageIcon,
    Smile,
    FileText,
    Calendar,
    Copy,
    ShieldCheck,
    AtSign,
    VolumeX,
    Ban,
    Hash,
    Bookmark,
    BookmarkPlus,
    BookmarkCheck,
    Library,
    Lock,
    Plus,
  } from "@lucide/svelte";

  export const icons = {
    feather: Feather,
    home: Home,
    login: LogIn,
    logout: LogOut,
    compose: PenLine,
    user: UserIcon,
    follow: UserPlus,
    unfollow: UserMinus,
    spinner: LoaderCircle,
    search: Search,
    settings: Settings,
    more: MoreHorizontal,
    read: BookOpen,
    sparkles: Sparkles,
    globe: Globe,
    clock: Clock,
    users: Users,
    bold: Bold,
    italic: Italic,
    strike: Strikethrough,
    code: Code,
    codeBlock: Code2,
    link: LinkIcon,
    hr: Minus,
    heading: Heading,
    h1: Heading1,
    h2: Heading2,
    h3: Heading3,
    h4: Heading4,
    h5: Heading5,
    h6: Heading6,
    paragraph: Pilcrow,
    list: List,
    orderedList: ListOrdered,
    quote: Quote,
    chevronDown: ChevronDown,
    sun: Sun,
    moon: Moon,
    monitor: Monitor,
    camera: Camera,
    edit: Pencil,
    close: X,
    heart: Heart,
    comment: MessageCircle,
    reply: Reply,
    trash: Trash2,
    share: Share,
    check: Check,
    image: ImageIcon,
    smile: Smile,
    draft: FileText,
    calendar: Calendar,
    copy: Copy,
    admin: ShieldCheck,
    at: AtSign,
    mute: VolumeX,
    block: Ban,
    tag: Hash,
    bookmark: Bookmark,
    bookmarkPlus: BookmarkPlus,
    bookmarkCheck: BookmarkCheck,
    library: Library,
    lock: Lock,
    plus: Plus,
  } as const;

  export type IconName = keyof typeof icons;
</script>

<script lang="ts">
  let {
    name,
    size = 20,
    class: className = "",
  }: { name: IconName; size?: number; class?: string } = $props();

  const Cmp = $derived(icons[name]);
</script>

<Cmp {size} class={className} />